
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 23 17:51:04 CET 2025
//----------------------------------------------------

package mini_turtle;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int IDENT = 2;
  public static final int EOF = 0;
}

